const HUBSPOT_API_KEY = 'HUBSPOT_API_KEY';
const HUBSPOT_CLIENT_ID = 'HUBSPOT_CLIENT_ID';
const HUBSPOT_CLIENT_SECRET = 'HUBSPOT_CLIENT_SECRET';
const HUBSPOT_PERSONAL_ACCESS_KEY = 'HUBSPOT_PERSONAL_ACCESS_KEY';
const HUBSPOT_PORTAL_ID = 'HUBSPOT_PORTAL_ID';

module.exports = {
  HUBSPOT_API_KEY,
  HUBSPOT_CLIENT_ID,
  HUBSPOT_CLIENT_SECRET,
  HUBSPOT_PERSONAL_ACCESS_KEY,
  HUBSPOT_PORTAL_ID,
};
